import { BasicData } from '../services/constants.service';

/** Según ISO 4217 */
export enum Currency {
  DIRHAM = 'AED',
  AFGHANI = 'AFN',
  LEK = 'ALL',
  DRAM = 'AMD',
  NETHERLANDS_ANTILLIAN_GUILDER = 'ANG',
  KWANZA = 'AOA',
  ARGENTINE_PESO = 'ARS',
  AUSTRALIAN_DOLLAR = 'AUD',
  ARUBAN_GUILDER = 'AWG',
  AZERBAIJANIAN_MANAT = 'AZM',
  CONVERTIBLE_MARK = 'BAM',
  BARBADOS_DOLLAR = 'BBD',
  BELARUSIAN_RUBLE = 'BYN',
  TAKA = 'BDT',
  BULGARIAN_LEV = 'BGN',
  BAHRAINI_DINAR = 'BHD',
  BURUNDI_FRANC = 'BIF',
  BERMUDIAN_DOLLAR__CUSTOMARILY__BERMUDA_DOLLAR_ = 'BMD',
  BRUNEI_DOLLAR = 'BND',
  BOLIVIANO = 'BOB',
  MVDOL = 'BOV',
  BRAZILIAN_REAL = 'BRL',
  BAHAMIAN_DOLLAR = 'BSD',
  NGULTRUM = 'BTN',
  PULA = 'BWP',
  BELARUSSIAN_RUBLE = 'BYR',
  BELIZE_DOLLAR = 'BZD',
  CANADIAN_DOLLAR = 'CAD',
  FRANC_CONGOLAIS = 'CDF',
  SWISS_FRANC = 'CHF',
  WIR_EURO = 'CHE',
  WIR_FRANC = 'CHW',
  CHILEAN_PESO = 'CLP',
  UNIDAD_DE_FOMENTO = 'CLF',
  YUAN_RENMINBI = 'CNY',
  COLOMBIAN_PESO = 'COP',
  UNIDAD_DE_VALOR_REAL = 'COU',
  COSTA_RICAN_COLON = 'CRC',
  CUBAN_PESO = 'CUP',
  PESO_CONVERTIBLE = 'CUC',
  CAPE_VERDE_ESCUDO = 'CVE',
  CYPRUS_POUND = 'CYP',
  CZECH_KORUNA = 'CZK',
  DJIBOUTI_FRANC = 'DJF',
  DANISH_KRONE = 'DKK',
  DOMINICAN_PESO = 'DOP',
  ALGERIAN_DINAR = 'DZD',
  KROON = 'EEK',
  EGYPTIAN_POUND = 'EGP',
  NAKFA = 'ERN',
  ETHOPIAN_BIRR = 'ETB',
  EURO = 'EUR',
  FIJI_DOLLAR = 'FJD',
  FALKLAND_ISLANDS_POUND = 'FKP',
  POUND_STERLING = 'GBP',
  LARI = 'GEL',
  GHANA_CEDI = 'GHS',
  CEDI = 'GHC',
  GIBRALTAR_POUND = 'GIP',
  DALASI = 'GMD',
  GUINEA_FRANC = 'GNF',
  QUETZAL = 'GTQ',
  GUYANA_DOLLAR = 'GYD',
  HONK_KONG_DOLLAR = 'HKD',
  LEMPIRA = 'HNL',
  KUNA = 'HRK',
  GOURDE = 'HTG',
  FORINT = 'HUF',
  RUPIAH = 'IDR',
  NEW_ISRAELI_SHEQEL = 'ILS',
  INDIAN_RUPEE = 'INR',
  IRAQI_DINAR = 'IQD',
  IRANIAN_RIAL = 'IRR',
  ICELAND_KRONA = 'ISK',
  JAMAICAN_DOLLAR = 'JMD',
  JORDANIAN_DINAR = 'JOD',
  YEN = 'JPY',
  KENYAN_SHILLING = 'KES',
  SOM = 'KGS',
  RIEL = 'KHR',
  COMORO_FRANC = 'KMF',
  NORTH_KOREAN_WON = 'KPW',
  WON = 'KRW',
  KUWAITI_DINAR = 'KWD',
  CAYMAN_ISLANDS_DOLLAR = 'KYD',
  TENGE = 'KZT',
  KIP = 'LAK',
  LEBANESE_POUND = 'LBP',
  SRI_LANKA_RUPEE = 'LKR',
  LIBERIAN_DOLLAR = 'LRD',
  LOTI = 'LSL',
  LITHUANIAN_LITAS = 'LTL',
  LATVIAN_LATS = 'LVL',
  LIBYAN_DINAR = 'LYD',
  MORROCAN_DIRHAM = 'MAD',
  MOZAMBIQUE_METICAL = 'MZN',
  MOLDOVAN_LEU = 'MDL',
  MALAGASY_FRANC = 'MGF',
  DENAR = 'MKD',
  MALAGASY_ARIARY = 'MGA',
  KYAT = 'MMK',
  TUGRIK = 'MNT',
  PATACA = 'MOP',
  /**@deprecated Codigo antiguo */
  OUGUIYA_OLD = 'MRO',
  MALTESE_LIRA = 'MTL',
  MAURITIUS_RUPEE = 'MUR',
  ADB_UNIT_OF_ACCOUNT = 'XUA',
  RUFIYAA = 'MVR',
  OUGUIYA = 'MRU',
  KWACHA_ZAMBIA = 'MMW',
  MEXICAN_PESO = 'MXN',
  MEXICAN_UNIDAD_DE_INVERSION = 'MXV',
  MALAYSIAN_RINGGIT = 'MYR',
  METICAL = 'MZM',
  NAMIBIA_DOLLAR = 'NAD',
  NAIRA = 'NGN',
  CORDOBA_ORO = 'NIO',
  NORWEGIAN_KRONE = 'NOK',
  NEPALESE_RUPEE = 'NPR',
  NEW_ZEALAND_DOLLAR = 'NZD',
  RIAL_OMANI = 'OMR',
  BALBOA = 'PAB',
  NUEVO_SOL = 'PEN',
  KINA = 'PGK',
  PHILIPPINE_PESO = 'PHP',
  PAKISTAN_RUPEE = 'PKR',
  ZLOTY = 'PLN',
  GUARANI = 'PYG',
  QATARI_RIAL = 'QAR',
  ROMANIAN_LEU = 'RON',
  LEU = 'ROL',
  RUSSIAN_RUBLE = 'RUB',
  RWANDA_FRANC = 'RWF',
  SAUDI_RIYAL = 'SAR',
  SERBIAN_DINAR = 'RSD',
  SOLOMON_ISLANDS_DOLLAR = 'SBD',
  SEYCHELLES_RUPEE = 'SCR',
  SUDANESE_DINAR = 'SDD',
  SUDANESE_POUND = 'SDG',
  SURINAM_DOLLAR = 'SRD',
  SWEDISH_KRONA = 'SEK',
  SINGAPORE_DOLLAR = 'SGD',
  ST__HELENA_POUND = 'SHP',
  TOLAR = 'SIT',
  SLOVAK_KORUNA = 'SKK',
  LEONE = 'SLL',
  SOMALI_SHILLING = 'SOS',
  SURINAME_GUILDER = 'SRG',
  SOUTH_SUDANESE_POUND = 'SSP',
  /**@deprecated Codigo antiguo */
  DOBRA_OLD = 'STD',
  EL_SALVADOR_COLON = 'SVC',
  SYRIAN_POUND = 'SYP',
  LILANGENI = 'SZL',
  BAHT = 'THB',
  SOMONI = 'TJS',
  MANAT = 'TMM',
  TUNISIAN_DINAR = 'TND',
  TURKISH_LIRA = 'TRY',
  TURKMENISTAN_NEW_MANAT = 'TMT',
  PA_APOS_ANGA = 'TOP',
  /**@deprecated Codigo antiguo */
  TURKISH_LIRA_OLD = 'TRL',
  TRINIDAD_AND_TOBAGO_DOLLAR = 'TTD',
  NEW_TAIWAN_DOLLAR = 'TWD',
  TANZANIAN_SHILLING = 'TZS',
  HRYVNIA = 'UAH',
  UGANDA_SHILLING = 'UGX',
  US_DOLLAR = 'USD',
  US_DOLLAR_NEXT_DAY_ = 'USN',
  PESO_URUGUAYO = 'UYU',
  URUGUAY_PESO_EN_UNIDADES_INDEXADAS_UI_ = 'UYI',
  UNIDAD_PREVISIONAL = 'UYW',
  UZBEKISTAN_SUM = 'UZS',
  BOLIVAR = 'VEB',
  DONG = 'VND',
  VATU = 'VUV',
  BOLIVAR_SOBERANO = 'VES',
  TALA = 'WST',
  DOBRA = 'STN',
  CFA_FRANC_CENTRAL = 'XAF',
  SILVER = 'XAG',
  GOLD = 'XAU',
  EAST_CARRIBEAN_DOLLAR = 'XCD',
  SDR = 'XDR',
  CFA_FRANC_OCCIDENTAL = 'XOF',
  PALLADIUM = 'XPD',
  CFP_FRANC = 'XPF',
  PLATINUM = 'XPT',
  SUCRE = 'XSU',
  BOND_MARKETS_UNIT_EUROPEAN_COMPOSITE_UNIT_EURCO_ = 'XBA',
  BOND_MARKETS_UNIT_EUROPEAN_MONETARY_UNIT_E_M_U__6_ = 'XBB',
  BOND_MARKETS_UNIT_EUROPEAN_UNIT_OF_ACCOUNT_17__E_U_A__17_ = 'XBC',
  CODES_SPECIFICALLY_RESERVED_FOR_TESTING_PURPOSES = 'XTS',
  THE_CODES_ASSIGNED_FOR_TRANSACTIONS_WHERE_NO_CURRENCY_IS_INVOLVED = 'XXX',
  YEMENI_RIAL = 'YER',
  NEW_DINAR = 'YUM',
  ZAMBIAN_KWACHA = 'ZMW',
  ZIMBABWE_DOLLAR = 'ZWL',
  RAND = 'ZAR',
  KWACHA_MALAWI = 'ZMK',
  /**@deprecated denominación del 2006 */
  ZIMBABWE_DOLLAR_2006 = 'ZWD',
}

export const currencies: BasicData<Currency>[] = [
  { code: Currency.DIRHAM, description: 'Dirham' },
  { code: Currency.AFGHANI, description: 'Afghani' },
  { code: Currency.LEK, description: 'Lek' },
  { code: Currency.DRAM, description: 'Dram' },
  { code: Currency.NETHERLANDS_ANTILLIAN_GUILDER, description: 'Netherlands Antillian Guilder' },
  { code: Currency.KWANZA, description: 'Kwanza' },
  { code: Currency.ARGENTINE_PESO, description: 'Argentine Peso' },
  { code: Currency.AUSTRALIAN_DOLLAR, description: 'Australian Dollar' },
  { code: Currency.ARUBAN_GUILDER, description: 'Aruban Guilder' },
  { code: Currency.AZERBAIJANIAN_MANAT, description: 'Azerbaijanian Manat' },
  { code: Currency.CONVERTIBLE_MARK, description: 'Convertible Mark' },
  { code: Currency.BARBADOS_DOLLAR, description: 'Barbados Dollar' },
  { code: Currency.BELARUSIAN_RUBLE, description: 'Belarusian Ruble' },
  { code: Currency.TAKA, description: 'Taka' },
  { code: Currency.BULGARIAN_LEV, description: 'Bulgarian Lev' },
  { code: Currency.BAHRAINI_DINAR, description: 'Bahraini Dinar' },
  { code: Currency.BURUNDI_FRANC, description: 'Burundi Franc' },
  {
    code: Currency.BERMUDIAN_DOLLAR__CUSTOMARILY__BERMUDA_DOLLAR_,
    description: 'Bermudian Dollar (customarily: Bermuda Dollar)',
  },
  { code: Currency.BRUNEI_DOLLAR, description: 'Brunei Dollar' },
  { code: Currency.BOLIVIANO, description: 'Boliviano' },
  { code: Currency.MVDOL, description: 'Mvdol' },
  { code: Currency.BRAZILIAN_REAL, description: 'Brazilian Real' },
  { code: Currency.BAHAMIAN_DOLLAR, description: 'Bahamian Dollar' },
  { code: Currency.NGULTRUM, description: 'Ngultrum' },
  { code: Currency.PULA, description: 'Pula' },
  { code: Currency.BELARUSSIAN_RUBLE, description: 'Belarussian Ruble' },
  { code: Currency.BELIZE_DOLLAR, description: 'Belize Dollar' },
  { code: Currency.CANADIAN_DOLLAR, description: 'Canadian Dollar' },
  { code: Currency.FRANC_CONGOLAIS, description: 'Franc Congolais' },
  { code: Currency.SWISS_FRANC, description: 'Swiss Franc' },
  { code: Currency.WIR_EURO, description: 'WIR Euro' },
  { code: Currency.WIR_FRANC, description: 'WIR Franc' },
  { code: Currency.CHILEAN_PESO, description: 'Chilean Peso' },
  { code: Currency.UNIDAD_DE_FOMENTO, description: 'Unidad de Fomento' },
  { code: Currency.YUAN_RENMINBI, description: 'Yuan Renminbi' },
  { code: Currency.COLOMBIAN_PESO, description: 'Colombian Peso' },
  { code: Currency.UNIDAD_DE_VALOR_REAL, description: 'Unidad de Valor Real' },
  { code: Currency.COSTA_RICAN_COLON, description: 'Costa Rican Colon' },
  { code: Currency.CUBAN_PESO, description: 'Cuban Peso' },
  { code: Currency.PESO_CONVERTIBLE, description: 'Peso Convertible' },
  { code: Currency.CAPE_VERDE_ESCUDO, description: 'Cape Verde Escudo' },
  { code: Currency.CYPRUS_POUND, description: 'Cyprus Pound' },
  { code: Currency.CZECH_KORUNA, description: 'Czech Koruna' },
  { code: Currency.DJIBOUTI_FRANC, description: 'Djibouti Franc' },
  { code: Currency.DANISH_KRONE, description: 'Danish Krone' },
  { code: Currency.DOMINICAN_PESO, description: 'Dominican Peso' },
  { code: Currency.ALGERIAN_DINAR, description: 'Algerian Dinar' },
  { code: Currency.KROON, description: 'Kroon' },
  { code: Currency.EGYPTIAN_POUND, description: 'Egyptian Pound' },
  { code: Currency.NAKFA, description: 'Nakfa' },
  { code: Currency.ETHOPIAN_BIRR, description: 'Ethopian Birr' },
  { code: Currency.EURO, description: 'Euro' },
  { code: Currency.FIJI_DOLLAR, description: 'Fiji Dollar' },
  { code: Currency.FALKLAND_ISLANDS_POUND, description: 'Falkland Islands Pound' },
  { code: Currency.POUND_STERLING, description: 'Pound Sterling' },
  { code: Currency.LARI, description: 'Lari' },
  { code: Currency.GHANA_CEDI, description: 'Ghana Cedi' },
  { code: Currency.CEDI, description: 'Cedi' },
  { code: Currency.GIBRALTAR_POUND, description: 'Gibraltar Pound' },
  { code: Currency.DALASI, description: 'Dalasi' },
  { code: Currency.GUINEA_FRANC, description: 'Guinea Franc' },
  { code: Currency.QUETZAL, description: 'Quetzal' },
  { code: Currency.GUYANA_DOLLAR, description: 'Guyana Dollar' },
  { code: Currency.HONK_KONG_DOLLAR, description: 'Honk Kong Dollar' },
  { code: Currency.LEMPIRA, description: 'Lempira' },
  { code: Currency.KUNA, description: 'Kuna' },
  { code: Currency.GOURDE, description: 'Gourde' },
  { code: Currency.FORINT, description: 'Forint' },
  { code: Currency.RUPIAH, description: 'Rupiah' },
  { code: Currency.NEW_ISRAELI_SHEQEL, description: 'New Israeli Sheqel' },
  { code: Currency.INDIAN_RUPEE, description: 'Indian Rupee' },
  { code: Currency.IRAQI_DINAR, description: 'Iraqi Dinar' },
  { code: Currency.IRANIAN_RIAL, description: 'Iranian Rial' },
  { code: Currency.ICELAND_KRONA, description: 'Iceland Krona' },
  { code: Currency.JAMAICAN_DOLLAR, description: 'Jamaican Dollar' },
  { code: Currency.JORDANIAN_DINAR, description: 'Jordanian Dinar' },
  { code: Currency.YEN, description: 'Yen' },
  { code: Currency.KENYAN_SHILLING, description: 'Kenyan Shilling' },
  { code: Currency.SOM, description: 'Som' },
  { code: Currency.RIEL, description: 'Riel' },
  { code: Currency.COMORO_FRANC, description: 'Comoro Franc' },
  { code: Currency.NORTH_KOREAN_WON, description: 'North Korean Won' },
  { code: Currency.WON, description: 'Won' },
  { code: Currency.KUWAITI_DINAR, description: 'Kuwaiti Dinar' },
  { code: Currency.CAYMAN_ISLANDS_DOLLAR, description: 'Cayman Islands Dollar' },
  { code: Currency.TENGE, description: 'Tenge' },
  { code: Currency.KIP, description: 'Kip' },
  { code: Currency.LEBANESE_POUND, description: 'Lebanese Pound' },
  { code: Currency.SRI_LANKA_RUPEE, description: 'Sri Lanka Rupee' },
  { code: Currency.LIBERIAN_DOLLAR, description: 'Liberian Dollar' },
  { code: Currency.LOTI, description: 'Loti' },
  { code: Currency.LITHUANIAN_LITAS, description: 'Lithuanian Litas' },
  { code: Currency.LATVIAN_LATS, description: 'Latvian Lats' },
  { code: Currency.LIBYAN_DINAR, description: 'Libyan Dinar' },
  { code: Currency.MORROCAN_DIRHAM, description: 'Morrocan Dirham' },
  { code: Currency.MOZAMBIQUE_METICAL, description: 'Mozambique Metical' },
  { code: Currency.MOLDOVAN_LEU, description: 'Moldovan Leu' },
  { code: Currency.MALAGASY_FRANC, description: 'Malagasy Franc' },
  { code: Currency.DENAR, description: 'Denar' },
  { code: Currency.MALAGASY_ARIARY, description: 'Malagasy Ariary' },
  { code: Currency.KYAT, description: 'Kyat' },
  { code: Currency.TUGRIK, description: 'Tugrik' },
  { code: Currency.PATACA, description: 'Pataca' },
  { code: Currency.OUGUIYA, description: 'Ouguiya' },
  { code: Currency.MALTESE_LIRA, description: 'Maltese Lira' },
  { code: Currency.MAURITIUS_RUPEE, description: 'Mauritius Rupee' },
  { code: Currency.ADB_UNIT_OF_ACCOUNT, description: 'ADB Unit of Account' },
  { code: Currency.RUFIYAA, description: 'Rufiyaa' },
  { code: Currency.OUGUIYA, description: 'Ouguiya' },
  { code: Currency.KWACHA_MALAWI, description: 'Kwacha' },
  { code: Currency.MEXICAN_PESO, description: 'Mexican Peso' },
  { code: Currency.MEXICAN_UNIDAD_DE_INVERSION, description: 'Mexican Unidad de Inversion' },
  { code: Currency.MALAYSIAN_RINGGIT, description: 'Malaysian Ringgit' },
  { code: Currency.METICAL, description: 'Metical' },
  { code: Currency.NAMIBIA_DOLLAR, description: 'Namibia Dollar' },
  { code: Currency.NAIRA, description: 'Naira' },
  { code: Currency.CORDOBA_ORO, description: 'Cordoba Oro' },
  { code: Currency.NORWEGIAN_KRONE, description: 'Norwegian Krone' },
  { code: Currency.NEPALESE_RUPEE, description: 'Nepalese Rupee' },
  { code: Currency.NEW_ZEALAND_DOLLAR, description: 'New Zealand Dollar' },
  { code: Currency.RIAL_OMANI, description: 'Rial Omani' },
  { code: Currency.BALBOA, description: 'Balboa' },
  { code: Currency.NUEVO_SOL, description: 'Nuevo Sol' },
  { code: Currency.KINA, description: 'Kina' },
  { code: Currency.PHILIPPINE_PESO, description: 'Philippine Peso' },
  { code: Currency.PAKISTAN_RUPEE, description: 'Pakistan Rupee' },
  { code: Currency.ZLOTY, description: 'Zloty' },
  { code: Currency.GUARANI, description: 'Guarani' },
  { code: Currency.QATARI_RIAL, description: 'Qatari Rial' },
  { code: Currency.ROMANIAN_LEU, description: 'Romanian Leu' },
  { code: Currency.LEU, description: 'Leu' },
  { code: Currency.RUSSIAN_RUBLE, description: 'Russian Ruble' },
  { code: Currency.RWANDA_FRANC, description: 'Rwanda Franc' },
  { code: Currency.SAUDI_RIYAL, description: 'Saudi Riyal' },
  { code: Currency.SERBIAN_DINAR, description: 'Serbian Dinar' },
  { code: Currency.SOLOMON_ISLANDS_DOLLAR, description: 'Solomon Islands Dollar' },
  { code: Currency.SEYCHELLES_RUPEE, description: 'Seychelles Rupee' },
  { code: Currency.SUDANESE_DINAR, description: 'Sudanese Dinar' },
  { code: Currency.SUDANESE_POUND, description: 'Sudanese Pound' },
  { code: Currency.SURINAM_DOLLAR, description: 'Surinam Dollar' },
  { code: Currency.SWEDISH_KRONA, description: 'Swedish Krona' },
  { code: Currency.SINGAPORE_DOLLAR, description: 'Singapore Dollar' },
  { code: Currency.ST__HELENA_POUND, description: 'St. Helena Pound' },
  { code: Currency.TOLAR, description: 'Tolar' },
  { code: Currency.SLOVAK_KORUNA, description: 'Slovak Koruna' },
  { code: Currency.LEONE, description: 'Leone' },
  { code: Currency.SOMALI_SHILLING, description: 'Somali Shilling' },
  { code: Currency.SURINAME_GUILDER, description: 'Suriname Guilder' },
  { code: Currency.SOUTH_SUDANESE_POUND, description: 'South Sudanese Pound' },
  { code: Currency.DOBRA, description: 'Dobra' },
  { code: Currency.EL_SALVADOR_COLON, description: 'El Salvador Colon' },
  { code: Currency.SYRIAN_POUND, description: 'Syrian Pound' },
  { code: Currency.LILANGENI, description: 'Lilangeni' },
  { code: Currency.BAHT, description: 'Baht' },
  { code: Currency.SOMONI, description: 'Somoni' },
  { code: Currency.MANAT, description: 'Manat' },
  { code: Currency.TUNISIAN_DINAR, description: 'Tunisian Dinar' },
  { code: Currency.TURKISH_LIRA, description: 'Turkish Lira' },
  { code: Currency.TURKMENISTAN_NEW_MANAT, description: 'Turkmenistan New Manat' },
  { code: Currency.PA_APOS_ANGA, description: 'Pa&apos;anga' },
  { code: Currency.TURKISH_LIRA, description: 'Turkish Lira' },
  { code: Currency.TRINIDAD_AND_TOBAGO_DOLLAR, description: 'Trinidad and Tobago Dollar' },
  { code: Currency.NEW_TAIWAN_DOLLAR, description: 'New Taiwan Dollar' },
  { code: Currency.TANZANIAN_SHILLING, description: 'Tanzanian Shilling' },
  { code: Currency.HRYVNIA, description: 'Hryvnia' },
  { code: Currency.UGANDA_SHILLING, description: 'Uganda Shilling' },
  { code: Currency.US_DOLLAR, description: 'US Dollar' },
  { code: Currency.US_DOLLAR_NEXT_DAY_, description: 'US Dollar(Next day)' },
  { code: Currency.PESO_URUGUAYO, description: 'Peso Uruguayo' },
  {
    code: Currency.URUGUAY_PESO_EN_UNIDADES_INDEXADAS_UI_,
    description: 'Uruguay Peso en Unidades Indexadas(UI)',
  },
  { code: Currency.UNIDAD_PREVISIONAL, description: 'Unidad Previsional' },
  { code: Currency.UZBEKISTAN_SUM, description: 'Uzbekistan Sum' },
  { code: Currency.BOLIVAR, description: 'Bolivar' },
  { code: Currency.DONG, description: 'Dong' },
  { code: Currency.VATU, description: 'Vatu' },
  { code: Currency.BOLIVAR_SOBERANO, description: 'Bolivar Soberano' },
  { code: Currency.TALA, description: 'Tala' },
  { code: Currency.DOBRA, description: 'Dobra' },
  { code: Currency.CFA_FRANC_CENTRAL, description: 'CFA Franc' },
  { code: Currency.SILVER, description: 'Silver' },
  { code: Currency.GOLD, description: 'Gold' },
  { code: Currency.EAST_CARRIBEAN_DOLLAR, description: 'East Carribean Dollar' },
  { code: Currency.SDR, description: 'SDR' },
  { code: Currency.CFA_FRANC_OCCIDENTAL, description: 'CFA Franc' },
  { code: Currency.PALLADIUM, description: 'Palladium' },
  { code: Currency.CFP_FRANC, description: 'CFP Franc' },
  { code: Currency.PLATINUM, description: 'Platinum' },
  { code: Currency.SUCRE, description: 'Sucre' },
  {
    code: Currency.BOND_MARKETS_UNIT_EUROPEAN_COMPOSITE_UNIT_EURCO_,
    description: 'Bond Markets Unit European Composite Unit(EURCO)',
  },
  {
    code: Currency.BOND_MARKETS_UNIT_EUROPEAN_MONETARY_UNIT_E_M_U__6_,
    description: 'Bond Markets Unit European Monetary Unit(E.M.U.-6)',
  },
  {
    code: Currency.BOND_MARKETS_UNIT_EUROPEAN_UNIT_OF_ACCOUNT_17__E_U_A__17_,
    description: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
  },
  {
    code: Currency.CODES_SPECIFICALLY_RESERVED_FOR_TESTING_PURPOSES,
    description: 'Codes specifically reserved for testing purposes',
  },
  {
    code: Currency.THE_CODES_ASSIGNED_FOR_TRANSACTIONS_WHERE_NO_CURRENCY_IS_INVOLVED,
    description: 'The codes assigned for transactions where no currency is involved',
  },
  { code: Currency.YEMENI_RIAL, description: 'Yemeni Rial' },
  { code: Currency.NEW_DINAR, description: 'New Dinar' },
  { code: Currency.ZAMBIAN_KWACHA, description: 'Zambian Kwacha' },
  { code: Currency.ZIMBABWE_DOLLAR, description: 'Zimbabwe Dollar' },
  { code: Currency.RAND, description: 'Rand' },
  { code: Currency.KWACHA_ZAMBIA, description: 'Kwacha' },
  { code: Currency.ZIMBABWE_DOLLAR, description: 'Zimbabwe Dollar' },
];
