import { BasicData } from '../services/constants.service';
import { Department } from './departments.constants';

type Data = BasicData<number> & { departamento: Department };
// TODO: reemplazar numero de departamento por enum del departamento
export const districts: Data[] = [
  { code: 1, description: 'ASUNCION (DISTRITO)', departamento: 1 },
  { code: 2, description: 'CONCEPCION (MUNICIPIO)', departamento: 2 },
  { code: 3, description: 'SAN LAZARO', departamento: 2 },
  { code: 4, description: 'SAN CARLOS', departamento: 2 },
  { code: 5, description: 'BELEN', departamento: 2 },
  { code: 6, description: 'LORETO', departamento: 2 },
  { code: 7, description: 'HORQUETA', departamento: 2 },
  { code: 8, description: 'SAN SALVADOR', departamento: 2 },
  { code: 9, description: "YBY YA'U", departamento: 2 },
  { code: 267, description: 'SAN CARLOS DEL APA', departamento: 2 },
  { code: 270, description: 'SARGENTO JOSE FELIX LOPEZ', departamento: 2 },
  { code: 280, description: 'PASO BARRETO (MUNICIPIO)', departamento: 2 },
  { code: 281, description: 'SAN ALFREDO (MUNICIPIO)', departamento: 2 },
  { code: 282, description: 'AZOTE¿Y (MUNICIPIO)', departamento: 2 },
  { code: 286, description: 'ARROYITO', departamento: 2 },
  { code: 10, description: 'SAN PEDRO DE YCUAMANDYYU', departamento: 3 },
  { code: 11, description: 'ANTEQUERA', departamento: 3 },
  { code: 12, description: 'GRAL. E.AQUINO', departamento: 3 },
  { code: 13, description: 'ITACURUBI DEL ROSARIO', departamento: 3 },
  { code: 14, description: 'SAN ESTANISLAO (SANTANI)', departamento: 3 },
  { code: 15, description: 'LIMA', departamento: 3 },
  { code: 16, description: 'NUEVA GERMANIA', departamento: 3 },
  { code: 17, description: 'TACUATI', departamento: 3 },
  { code: 18, description: 'UNION', departamento: 3 },
  { code: 19, description: '25 DE DICIEMBRE', departamento: 3 },
  { code: 20, description: 'VILLA DEL ROSARIO', departamento: 3 },
  { code: 21, description: 'YATAITY DEL NORTE', departamento: 3 },
  { code: 22, description: 'ISIDORO RESQUIN', departamento: 3 },
  { code: 23, description: 'CHORE', departamento: 3 },
  { code: 24, description: 'SAN PABLO', departamento: 3 },
  { code: 25, description: 'SAN JOSE DEL ROSARIO', departamento: 3 },
  { code: 220, description: 'GUAYAIBI', departamento: 3 },
  { code: 226, description: 'CAPIIBARY', departamento: 3 },
  { code: 245, description: 'YRYBUCUA', departamento: 3 },
  { code: 263, description: 'SANTA ROSA DEL AGUARAY', departamento: 3 },
  { code: 268, description: 'LIBERACIÓN', departamento: 3 },
  { code: 285, description: 'SAN VICENTE PANCHOLO', departamento: 3 },
  { code: 26, description: 'CAACUPE', departamento: 4 },
  { code: 27, description: 'ALTOS', departamento: 4 },
  { code: 28, description: 'ARROYOS Y ESTEROS', departamento: 4 },
  { code: 29, description: 'ATYRA', departamento: 4 },
  { code: 30, description: 'CARAGUATAY', departamento: 4 },
  { code: 31, description: 'EMBOSCADA', departamento: 4 },
  { code: 32, description: 'EUSEBIO AYALA', departamento: 4 },
  { code: 33, description: 'ISLA PUCU', departamento: 4 },
  { code: 34, description: 'ITACURUBI DE LA CORDILLERA', departamento: 4 },
  { code: 35, description: 'JUAN DE MENA', departamento: 4 },
  { code: 36, description: 'NUEVA COLOMBIA', departamento: 4 },
  { code: 37, description: 'PIRIBEBUY', departamento: 4 },
  { code: 38, description: '1RO.DE MARZO', departamento: 4 },
  { code: 39, description: 'SAN BERNARDINO', departamento: 4 },
  { code: 40, description: 'SANTA ELENA', departamento: 4 },
  { code: 41, description: 'TOBATI', departamento: 4 },
  { code: 42, description: 'VALENZUELA', departamento: 4 },
  { code: 43, description: 'LOMA GRANDE', departamento: 4 },
  { code: 44, description: 'SAN JOSE OBRERO', departamento: 4 },
  { code: 214, description: 'MBOCAYATY DEL YHAGUY', departamento: 4 },
  { code: 45, description: 'VILLARRICA', departamento: 5 },
  { code: 46, description: 'SAN SALVADOR', departamento: 5 },
  { code: 47, description: 'BORJA', departamento: 5 },
  { code: 48, description: 'INDEPENDENCIA (R.D.MELGAREJO)', departamento: 5 },
  { code: 49, description: 'GRAL.EUGENIO A. GARAY', departamento: 5 },
  { code: 50, description: 'CNEL. MARTINEZ', departamento: 5 },
  { code: 51, description: 'JOSE FASSARDI', departamento: 5 },
  { code: 52, description: 'FELIX PEREZ CARDOZO', departamento: 5 },
  { code: 53, description: 'MAURICIO JOSE TROCHE', departamento: 5 },
  { code: 54, description: 'ITAPE', departamento: 5 },
  { code: 55, description: 'ITURBE', departamento: 5 },
  { code: 56, description: 'MBOCAYATY', departamento: 5 },
  { code: 57, description: 'NATALICIO TALAVERA', departamento: 5 },
  { code: 58, description: 'ÑUMI', departamento: 5 },
  { code: 59, description: 'YATAITY', departamento: 5 },
  { code: 60, description: 'DR. BOTREL', departamento: 5 },
  { code: 225, description: 'PASO YOBAY', departamento: 5 },
  { code: 246, description: 'SIN EQUIVALENCIA', departamento: 5 },
  { code: 265, description: 'TEBICUARY', departamento: 5 },
  { code: 61, description: 'CNEL. OVIEDO', departamento: 6 },
  { code: 62, description: 'CAAGUAZU', departamento: 6 },
  { code: 63, description: 'CARAYAO', departamento: 6 },
  { code: 64, description: 'CECILIO BAEZ', departamento: 6 },
  { code: 65, description: 'NUEVA LONDRES', departamento: 6 },
  { code: 66, description: 'SAN JOAQUIN', departamento: 6 },
  { code: 67, description: 'SAN JOSE DE LOS ARROYOS', departamento: 6 },
  { code: 68, description: 'YHU', departamento: 6 },
  { code: 69, description: 'JUAN MANUEL FRUTOS', departamento: 6 },
  { code: 70, description: 'REPATRIACION', departamento: 6 },
  { code: 71, description: 'SANTA ROSA DEL MBUTUY', departamento: 6 },
  { code: 72, description: 'J. EULOGIO ESTIGARRIBIA', departamento: 6 },
  { code: 73, description: 'JOSE D. OCAMPOS', departamento: 6 },
  { code: 74, description: 'R.I.3 CORRALES', departamento: 6 },
  { code: 75, description: 'RAUL A. OVIEDO', departamento: 6 },
  { code: 76, description: 'MCAL.F.SOLANO LOPEZ', departamento: 6 },
  { code: 227, description: '3 DE FEBRERO', departamento: 6 },
  { code: 228, description: 'SIMON BOLIVAR', departamento: 6 },
  { code: 229, description: 'LA PASTORA', departamento: 6 },
  { code: 237, description: 'VAQUERIA', departamento: 6 },
  { code: 244, description: 'ESCULIES', departamento: 6 },
  { code: 275, description: 'TEMBIAPORA', departamento: 6 },
  { code: 276, description: 'NUEVA TOLEDO', departamento: 6 },
  { code: 77, description: 'CAAZAPA', departamento: 7 },
  { code: 78, description: 'BUENA VISTA', departamento: 7 },
  { code: 79, description: 'GRAL. H. MORINIGO', departamento: 7 },
  { code: 80, description: 'MACIEL', departamento: 7 },
  { code: 81, description: 'MOISES BERTONI', departamento: 7 },
  { code: 82, description: 'SAN JUAN NEPOMUCENO', departamento: 7 },
  { code: 83, description: 'ABAI', departamento: 7 },
  { code: 84, description: 'TAVAI', departamento: 7 },
  { code: 85, description: 'YEGROS', departamento: 7 },
  { code: 86, description: 'YUTY', departamento: 7 },
  { code: 272, description: '3 DE MAYO', departamento: 7 },
  { code: 87, description: 'ENCARNACION', departamento: 8 },
  { code: 88, description: 'BELLA VISTA', departamento: 8 },
  { code: 89, description: 'CAMBYRETA', departamento: 8 },
  { code: 90, description: 'CAPITAN MEZA', departamento: 8 },
  { code: 91, description: 'CARMEN DEL PARANA', departamento: 8 },
  { code: 92, description: 'CAPITAN MIRANDA', departamento: 8 },
  { code: 93, description: 'CORONEL BOGADO', departamento: 8 },
  { code: 94, description: 'FRAM', departamento: 8 },
  { code: 95, description: 'GRAL. ARTIGAS', departamento: 8 },
  { code: 96, description: 'GRAL. DELGADO', departamento: 8 },
  { code: 97, description: 'HOHENAU', departamento: 8 },
  { code: 98, description: 'JESUS', departamento: 8 },
  { code: 99, description: 'OBLIGADO', departamento: 8 },
  { code: 100, description: 'SAN COSME Y DAMIAN', departamento: 8 },
  { code: 101, description: 'SAN PEDRO DEL PARANA', departamento: 8 },
  { code: 102, description: 'NUEVA ALBORADA', departamento: 8 },
  { code: 103, description: 'TRINIDAD', departamento: 8 },
  { code: 104, description: 'NATALIO', departamento: 8 },
  { code: 105, description: 'JOSE LEANDRO OVIEDO', departamento: 8 },
  { code: 106, description: 'SAN RAFAEL DEL PARANA', departamento: 8 },
  { code: 107, description: 'CARLOS A. LOPEZ', departamento: 8 },
  { code: 108, description: 'JULIO D. OTAÑO', departamento: 8 },
  { code: 109, description: 'EDELIRA', departamento: 8 },
  { code: 110, description: 'SAN JUAN DEL PARANA', departamento: 8 },
  { code: 111, description: 'LA PAZ', departamento: 8 },
  { code: 112, description: 'TOMAS R. PEREIRA', departamento: 8 },
  { code: 113, description: 'YATYTAY', departamento: 8 },
  { code: 114, description: 'HERIBERTA S.DE IGLESIAS', departamento: 8 },
  { code: 221, description: 'PIRAPO', departamento: 8 },
  { code: 232, description: 'ITAPUA POTY', departamento: 8 },
  { code: 243, description: 'FEDERICO CHAVEZ', departamento: 8 },
  { code: 262, description: 'ALTO VERA', departamento: 8 },
  { code: 115, description: 'SAN JUAN BAUTISTA', departamento: 9 },
  { code: 116, description: 'AYOLAS', departamento: 9 },
  { code: 117, description: 'SAN IGNACIO', departamento: 9 },
  { code: 118, description: 'SAN MIGUEL', departamento: 9 },
  { code: 119, description: 'SAN PATRICIO', departamento: 9 },
  { code: 120, description: 'SANTIAGO', departamento: 9 },
  { code: 121, description: 'SANTA MARIA', departamento: 9 },
  { code: 122, description: 'SANTA ROSA', departamento: 9 },
  { code: 123, description: 'VILLA FLORIDA', departamento: 9 },
  { code: 124, description: 'YABEBYRY', departamento: 9 },
  { code: 125, description: 'PARAGUARI', departamento: 10 },
  { code: 126, description: 'ACAHAY', departamento: 10 },
  { code: 127, description: 'CAAPUCU', departamento: 10 },
  { code: 128, description: 'CABALLERO', departamento: 10 },
  { code: 129, description: 'CARAPEGUA', departamento: 10 },
  { code: 130, description: 'LA COLMENA', departamento: 10 },
  { code: 131, description: 'ESCOBAR', departamento: 10 },
  { code: 132, description: 'MBUYAPEY', departamento: 10 },
  { code: 133, description: 'PIRAYU', departamento: 10 },
  { code: 134, description: 'QUIINDY', departamento: 10 },
  { code: 135, description: 'ROQUE GONZALEZ', departamento: 10 },
  { code: 136, description: 'SAPUCAI', departamento: 10 },
  { code: 137, description: 'YBYCUI', departamento: 10 },
  { code: 138, description: 'QUYQUYHO', departamento: 10 },
  { code: 139, description: 'YBYTYMI', departamento: 10 },
  { code: 140, description: 'TEBICUARY MI', departamento: 10 },
  { code: 141, description: 'YAGUARON', departamento: 10 },
  { code: 142, description: 'HERNANDARIAS', departamento: 11 },
  { code: 143, description: 'DOMINGO MARTINEZ DE IRALA', departamento: 11 },
  { code: 144, description: 'ÑACUNDAY', departamento: 11 },
  { code: 145, description: 'CIUDAD DEL ESTE', departamento: 11 },
  { code: 146, description: 'JUAN LEON MALLORQUIN', departamento: 11 },
  { code: 147, description: 'ITAKYRY', departamento: 11 },
  { code: 148, description: "JUAN E.O'LEARY", departamento: 11 },
  { code: 149, description: 'PRESIDENTE FRANCO', departamento: 11 },
  { code: 150, description: 'YGUAZU', departamento: 11 },
  { code: 151, description: 'SAN CRISTOBAL', departamento: 11 },
  { code: 209, description: 'SANTA RITA', departamento: 11 },
  { code: 210, description: 'MINGA GUAZU', departamento: 11 },
  { code: 211, description: 'LOS CEDRALES', departamento: 11 },
  { code: 212, description: 'SAN ALBERTO', departamento: 11 },
  { code: 213, description: 'MINGA PORA', departamento: 11 },
  { code: 215, description: 'NARANJAL', departamento: 11 },
  { code: 216, description: 'SANTA ROSA DEL MONDAY', departamento: 11 },
  { code: 217, description: 'IRUÑA', departamento: 11 },
  { code: 219, description: 'MBARACAYU', departamento: 11 },
  { code: 239, description: 'SANTA FE DEL PARANA', departamento: 11 },
  { code: 240, description: 'NUEVA ESPERANZA', departamento: 11 },
  { code: 269, description: 'TAVAPY', departamento: 11 },
  { code: 273, description: 'DR. RAUL PEÑA', departamento: 11 },
  { code: 152, description: 'AREGUA', departamento: 12 },
  { code: 153, description: 'CAPIATA', departamento: 12 },
  { code: 154, description: 'FERNANDO DE LA MORA', departamento: 12 },
  { code: 155, description: 'GUARAMBARE', departamento: 12 },
  { code: 156, description: 'ITA', departamento: 12 },
  { code: 157, description: 'ITAUGUA', departamento: 12 },
  { code: 158, description: 'LIMPIO', departamento: 12 },
  { code: 159, description: 'LUQUE', departamento: 12 },
  { code: 160, description: 'MARIANO ROQUE ALONSO', departamento: 12 },
  { code: 161, description: 'ÑEMBY', departamento: 12 },
  { code: 162, description: 'NUEVA ITALIA', departamento: 12 },
  { code: 163, description: 'SAN ANTONIO', departamento: 12 },
  { code: 164, description: 'SAN LORENZO', departamento: 12 },
  { code: 165, description: 'VILLA ELISA', departamento: 12 },
  { code: 166, description: 'VILLETA', departamento: 12 },
  { code: 167, description: 'YPACARAI', departamento: 12 },
  { code: 168, description: 'YPANE', departamento: 12 },
  { code: 169, description: 'LAMBARE', departamento: 12 },
  { code: 170, description: 'J.AUGUSTO SALDIVAR', departamento: 12 },
  { code: 277, description: 'LOMA PYTA', departamento: 12 },
  { code: 171, description: 'PILAR', departamento: 13 },
  { code: 172, description: 'ALBERDI', departamento: 13 },
  { code: 173, description: 'CERRITO', departamento: 13 },
  { code: 174, description: 'DESMOCHADOS', departamento: 13 },
  { code: 175, description: 'GUAZU CUA', departamento: 13 },
  { code: 176, description: 'HUMAITA', departamento: 13 },
  { code: 177, description: 'ISLA UMBU', departamento: 13 },
  { code: 178, description: 'LAURELES', departamento: 13 },
  { code: 179, description: 'PASO DE PATRIA', departamento: 13 },
  { code: 180, description: 'MAYOR J.D.MARTINEZ', departamento: 13 },
  { code: 181, description: 'SAN JUAN DE ÑEEMBUCU', departamento: 13 },
  { code: 182, description: 'TACUARAS', departamento: 13 },
  { code: 183, description: 'VILLA OLIVA', departamento: 13 },
  { code: 184, description: 'VILLALBIN', departamento: 13 },
  { code: 203, description: 'GRAL.JOSE EDUVIGIS DIAZ', departamento: 13 },
  { code: 205, description: 'VILLA FRANCA', departamento: 13 },
  { code: 230, description: 'VILLA FRANCA', departamento: 13 },
  { code: 231, description: 'VILLALBIN', departamento: 13 },
  { code: 185, description: 'PEDRO JUAN CABALLERO', departamento: 14 },
  { code: 186, description: 'BELLA VISTA', departamento: 14 },
  { code: 187, description: 'CAPITAN BADO', departamento: 14 },
  { code: 278, description: 'KARAPAI', departamento: 14 },
  { code: 279, description: 'ZANJA PYTA', departamento: 14 },
  { code: 188, description: 'VILLA HAYES', departamento: 15 },
  { code: 189, description: 'BENJAMIN ACEVAL(MONTE SOCIEDAD', departamento: 15 },
  { code: 190, description: 'PTO.PINAZCO', departamento: 15 },
  { code: 191, description: 'NANAWA', departamento: 15 },
  { code: 206, description: 'POZO COLORADO', departamento: 15 },
  { code: 242, description: 'JOSE FALCON', departamento: 15 },
  { code: 261, description: 'TTE. 1RO. IRALA FERNANDEZ', departamento: 15 },
  { code: 264, description: 'TENIENTE ESTEBAN MARTINEZ', departamento: 15 },
  { code: 192, description: 'MCAL.ESTIGARRIBIA', departamento: 16 },
  { code: 193, description: 'BOQUERON', departamento: 16 },
  { code: 194, description: 'PEDRO P.PEÑA', departamento: 16 },
  { code: 234, description: 'GRAL. EUGENIO A. GARAY', departamento: 16 },
  { code: 259, description: 'FILADELFIA', departamento: 16 },
  { code: 260, description: 'LOMA PLATA', departamento: 16 },
  { code: 195, description: 'FUERTE OLIMPO', departamento: 17 },
  { code: 196, description: 'BAHIA NEGRA', departamento: 17 },
  { code: 218, description: 'PUERTO CASADO', departamento: 17 },
  { code: 223, description: 'PUERTO GUARANI', departamento: 17 },
  { code: 233, description: 'MAYOR PABLO LAGERENZA', departamento: 17 },
  { code: 266, description: 'CARMELO PERALTA', departamento: 17 },
  { code: 197, description: 'SAN ISIDRO DEL CURUGUATY', departamento: 18 },
  { code: 198, description: 'VILLA YGATIMI', departamento: 18 },
  { code: 199, description: 'YPEJHU', departamento: 18 },
  { code: 200, description: 'CORPUS CHRISTI', departamento: 18 },
  { code: 201, description: 'ITANARA', departamento: 18 },
  { code: 202, description: 'FRANCISCO CABALLERO ALVAREZ', departamento: 18 },
  { code: 207, description: 'SALTO DEL GUAIRA', departamento: 18 },
  { code: 235, description: 'LA PALOMA', departamento: 18 },
  { code: 236, description: 'KATUETE', departamento: 18 },
  { code: 238, description: 'NUEVA ESPERANZA', departamento: 18 },
  { code: 241, description: 'YASY KAÑY', departamento: 18 },
  { code: 271, description: 'YBYRAROBANA', departamento: 18 },
  { code: 274, description: 'YBY PYTA', departamento: 18 },
  { code: 283, description: 'MARACANA', departamento: 18 },
  { code: 284, description: 'PUERTO ADELA', departamento: 18 },
]