import { BasicData } from '../services/constants.service';
import { Department } from './departments.constants';

type Data = BasicData<number> & { department: Department };
export const districts: Data[] = [
  { _id: 1, description: 'ASUNCION (DISTRITO)', department: 1 },
  { _id: 2, description: 'CONCEPCION (MUNICIPIO)', department: 2 },
  { _id: 3, description: 'SAN LAZARO', department: 2 },
  { _id: 4, description: 'SAN CARLOS', department: 2 },
  { _id: 5, description: 'BELEN', department: 2 },
  { _id: 6, description: 'LORETO', department: 2 },
  { _id: 7, description: 'HORQUETA', department: 2 },
  { _id: 8, description: 'SAN SALVADOR', department: 2 },
  { _id: 9, description: "YBY YA'U", department: 2 },
  { _id: 267, description: 'SAN CARLOS DEL APA', department: 2 },
  { _id: 270, description: 'SARGENTO JOSE FELIX LOPEZ', department: 2 },
  { _id: 280, description: 'PASO BARRETO (MUNICIPIO)', department: 2 },
  { _id: 281, description: 'SAN ALFREDO (MUNICIPIO)', department: 2 },
  { _id: 282, description: 'AZOTE¿Y (MUNICIPIO)', department: 2 },
  { _id: 286, description: 'ARROYITO', department: 2 },
  { _id: 10, description: 'SAN PEDRO DE YCUAMANDYYU', department: 3 },
  { _id: 11, description: 'ANTEQUERA', department: 3 },
  { _id: 12, description: 'GRAL. E.AQUINO', department: 3 },
  { _id: 13, description: 'ITACURUBI DEL ROSARIO', department: 3 },
  { _id: 14, description: 'SAN ESTANISLAO (SANTANI)', department: 3 },
  { _id: 15, description: 'LIMA', department: 3 },
  { _id: 16, description: 'NUEVA GERMANIA', department: 3 },
  { _id: 17, description: 'TACUATI', department: 3 },
  { _id: 18, description: 'UNION', department: 3 },
  { _id: 19, description: '25 DE DICIEMBRE', department: 3 },
  { _id: 20, description: 'VILLA DEL ROSARIO', department: 3 },
  { _id: 21, description: 'YATAITY DEL NORTE', department: 3 },
  { _id: 22, description: 'ISIDORO RESQUIN', department: 3 },
  { _id: 23, description: 'CHORE', department: 3 },
  { _id: 24, description: 'SAN PABLO', department: 3 },
  { _id: 25, description: 'SAN JOSE DEL ROSARIO', department: 3 },
  { _id: 220, description: 'GUAYAIBI', department: 3 },
  { _id: 226, description: 'CAPIIBARY', department: 3 },
  { _id: 245, description: 'YRYBUCUA', department: 3 },
  { _id: 263, description: 'SANTA ROSA DEL AGUARAY', department: 3 },
  { _id: 268, description: 'LIBERACIÓN', department: 3 },
  { _id: 285, description: 'SAN VICENTE PANCHOLO', department: 3 },
  { _id: 26, description: 'CAACUPE', department: 4 },
  { _id: 27, description: 'ALTOS', department: 4 },
  { _id: 28, description: 'ARROYOS Y ESTEROS', department: 4 },
  { _id: 29, description: 'ATYRA', department: 4 },
  { _id: 30, description: 'CARAGUATAY', department: 4 },
  { _id: 31, description: 'EMBOSCADA', department: 4 },
  { _id: 32, description: 'EUSEBIO AYALA', department: 4 },
  { _id: 33, description: 'ISLA PUCU', department: 4 },
  { _id: 34, description: 'ITACURUBI DE LA CORDILLERA', department: 4 },
  { _id: 35, description: 'JUAN DE MENA', department: 4 },
  { _id: 36, description: 'NUEVA COLOMBIA', department: 4 },
  { _id: 37, description: 'PIRIBEBUY', department: 4 },
  { _id: 38, description: '1RO.DE MARZO', department: 4 },
  { _id: 39, description: 'SAN BERNARDINO', department: 4 },
  { _id: 40, description: 'SANTA ELENA', department: 4 },
  { _id: 41, description: 'TOBATI', department: 4 },
  { _id: 42, description: 'VALENZUELA', department: 4 },
  { _id: 43, description: 'LOMA GRANDE', department: 4 },
  { _id: 44, description: 'SAN JOSE OBRERO', department: 4 },
  { _id: 214, description: 'MBOCAYATY DEL YHAGUY', department: 4 },
  { _id: 45, description: 'VILLARRICA', department: 5 },
  { _id: 46, description: 'SAN SALVADOR', department: 5 },
  { _id: 47, description: 'BORJA', department: 5 },
  { _id: 48, description: 'INDEPENDENCIA (R.D.MELGAREJO)', department: 5 },
  { _id: 49, description: 'GRAL.EUGENIO A. GARAY', department: 5 },
  { _id: 50, description: 'CNEL. MARTINEZ', department: 5 },
  { _id: 51, description: 'JOSE FASSARDI', department: 5 },
  { _id: 52, description: 'FELIX PEREZ CARDOZO', department: 5 },
  { _id: 53, description: 'MAURICIO JOSE TROCHE', department: 5 },
  { _id: 54, description: 'ITAPE', department: 5 },
  { _id: 55, description: 'ITURBE', department: 5 },
  { _id: 56, description: 'MBOCAYATY', department: 5 },
  { _id: 57, description: 'NATALICIO TALAVERA', department: 5 },
  { _id: 58, description: 'ÑUMI', department: 5 },
  { _id: 59, description: 'YATAITY', department: 5 },
  { _id: 60, description: 'DR. BOTREL', department: 5 },
  { _id: 225, description: 'PASO YOBAY', department: 5 },
  { _id: 246, description: 'SIN EQUIVALENCIA', department: 5 },
  { _id: 265, description: 'TEBICUARY', department: 5 },
  { _id: 61, description: 'CNEL. OVIEDO', department: 6 },
  { _id: 62, description: 'CAAGUAZU', department: 6 },
  { _id: 63, description: 'CARAYAO', department: 6 },
  { _id: 64, description: 'CECILIO BAEZ', department: 6 },
  { _id: 65, description: 'NUEVA LONDRES', department: 6 },
  { _id: 66, description: 'SAN JOAQUIN', department: 6 },
  { _id: 67, description: 'SAN JOSE DE LOS ARROYOS', department: 6 },
  { _id: 68, description: 'YHU', department: 6 },
  { _id: 69, description: 'JUAN MANUEL FRUTOS', department: 6 },
  { _id: 70, description: 'REPATRIACION', department: 6 },
  { _id: 71, description: 'SANTA ROSA DEL MBUTUY', department: 6 },
  { _id: 72, description: 'J. EULOGIO ESTIGARRIBIA', department: 6 },
  { _id: 73, description: 'JOSE D. OCAMPOS', department: 6 },
  { _id: 74, description: 'R.I.3 CORRALES', department: 6 },
  { _id: 75, description: 'RAUL A. OVIEDO', department: 6 },
  { _id: 76, description: 'MCAL.F.SOLANO LOPEZ', department: 6 },
  { _id: 227, description: '3 DE FEBRERO', department: 6 },
  { _id: 228, description: 'SIMON BOLIVAR', department: 6 },
  { _id: 229, description: 'LA PASTORA', department: 6 },
  { _id: 237, description: 'VAQUERIA', department: 6 },
  { _id: 244, description: 'ESCULIES', department: 6 },
  { _id: 275, description: 'TEMBIAPORA', department: 6 },
  { _id: 276, description: 'NUEVA TOLEDO', department: 6 },
  { _id: 77, description: 'CAAZAPA', department: 7 },
  { _id: 78, description: 'BUENA VISTA', department: 7 },
  { _id: 79, description: 'GRAL. H. MORINIGO', department: 7 },
  { _id: 80, description: 'MACIEL', department: 7 },
  { _id: 81, description: 'MOISES BERTONI', department: 7 },
  { _id: 82, description: 'SAN JUAN NEPOMUCENO', department: 7 },
  { _id: 83, description: 'ABAI', department: 7 },
  { _id: 84, description: 'TAVAI', department: 7 },
  { _id: 85, description: 'YEGROS', department: 7 },
  { _id: 86, description: 'YUTY', department: 7 },
  { _id: 272, description: '3 DE MAYO', department: 7 },
  { _id: 87, description: 'ENCARNACION', department: 8 },
  { _id: 88, description: 'BELLA VISTA', department: 8 },
  { _id: 89, description: 'CAMBYRETA', department: 8 },
  { _id: 90, description: 'CAPITAN MEZA', department: 8 },
  { _id: 91, description: 'CARMEN DEL PARANA', department: 8 },
  { _id: 92, description: 'CAPITAN MIRANDA', department: 8 },
  { _id: 93, description: 'CORONEL BOGADO', department: 8 },
  { _id: 94, description: 'FRAM', department: 8 },
  { _id: 95, description: 'GRAL. ARTIGAS', department: 8 },
  { _id: 96, description: 'GRAL. DELGADO', department: 8 },
  { _id: 97, description: 'HOHENAU', department: 8 },
  { _id: 98, description: 'JESUS', department: 8 },
  { _id: 99, description: 'OBLIGADO', department: 8 },
  { _id: 100, description: 'SAN COSME Y DAMIAN', department: 8 },
  { _id: 101, description: 'SAN PEDRO DEL PARANA', department: 8 },
  { _id: 102, description: 'NUEVA ALBORADA', department: 8 },
  { _id: 103, description: 'TRINIDAD', department: 8 },
  { _id: 104, description: 'NATALIO', department: 8 },
  { _id: 105, description: 'JOSE LEANDRO OVIEDO', department: 8 },
  { _id: 106, description: 'SAN RAFAEL DEL PARANA', department: 8 },
  { _id: 107, description: 'CARLOS A. LOPEZ', department: 8 },
  { _id: 108, description: 'JULIO D. OTAÑO', department: 8 },
  { _id: 109, description: 'EDELIRA', department: 8 },
  { _id: 110, description: 'SAN JUAN DEL PARANA', department: 8 },
  { _id: 111, description: 'LA PAZ', department: 8 },
  { _id: 112, description: 'TOMAS R. PEREIRA', department: 8 },
  { _id: 113, description: 'YATYTAY', department: 8 },
  { _id: 114, description: 'HERIBERTA S.DE IGLESIAS', department: 8 },
  { _id: 221, description: 'PIRAPO', department: 8 },
  { _id: 232, description: 'ITAPUA POTY', department: 8 },
  { _id: 243, description: 'FEDERICO CHAVEZ', department: 8 },
  { _id: 262, description: 'ALTO VERA', department: 8 },
  { _id: 115, description: 'SAN JUAN BAUTISTA', department: 9 },
  { _id: 116, description: 'AYOLAS', department: 9 },
  { _id: 117, description: 'SAN IGNACIO', department: 9 },
  { _id: 118, description: 'SAN MIGUEL', department: 9 },
  { _id: 119, description: 'SAN PATRICIO', department: 9 },
  { _id: 120, description: 'SANTIAGO', department: 9 },
  { _id: 121, description: 'SANTA MARIA', department: 9 },
  { _id: 122, description: 'SANTA ROSA', department: 9 },
  { _id: 123, description: 'VILLA FLORIDA', department: 9 },
  { _id: 124, description: 'YABEBYRY', department: 9 },
  { _id: 125, description: 'PARAGUARI', department: 10 },
  { _id: 126, description: 'ACAHAY', department: 10 },
  { _id: 127, description: 'CAAPUCU', department: 10 },
  { _id: 128, description: 'CABALLERO', department: 10 },
  { _id: 129, description: 'CARAPEGUA', department: 10 },
  { _id: 130, description: 'LA COLMENA', department: 10 },
  { _id: 131, description: 'ESCOBAR', department: 10 },
  { _id: 132, description: 'MBUYAPEY', department: 10 },
  { _id: 133, description: 'PIRAYU', department: 10 },
  { _id: 134, description: 'QUIINDY', department: 10 },
  { _id: 135, description: 'ROQUE GONZALEZ', department: 10 },
  { _id: 136, description: 'SAPUCAI', department: 10 },
  { _id: 137, description: 'YBYCUI', department: 10 },
  { _id: 138, description: 'QUYQUYHO', department: 10 },
  { _id: 139, description: 'YBYTYMI', department: 10 },
  { _id: 140, description: 'TEBICUARY MI', department: 10 },
  { _id: 141, description: 'YAGUARON', department: 10 },
  { _id: 142, description: 'HERNANDARIAS', department: 11 },
  { _id: 143, description: 'DOMINGO MARTINEZ DE IRALA', department: 11 },
  { _id: 144, description: 'ÑACUNDAY', department: 11 },
  { _id: 145, description: 'CIUDAD DEL ESTE', department: 11 },
  { _id: 146, description: 'JUAN LEON MALLORQUIN', department: 11 },
  { _id: 147, description: 'ITAKYRY', department: 11 },
  { _id: 148, description: "JUAN E.O'LEARY", department: 11 },
  { _id: 149, description: 'PRESIDENTE FRANCO', department: 11 },
  { _id: 150, description: 'YGUAZU', department: 11 },
  { _id: 151, description: 'SAN CRISTOBAL', department: 11 },
  { _id: 209, description: 'SANTA RITA', department: 11 },
  { _id: 210, description: 'MINGA GUAZU', department: 11 },
  { _id: 211, description: 'LOS CEDRALES', department: 11 },
  { _id: 212, description: 'SAN ALBERTO', department: 11 },
  { _id: 213, description: 'MINGA PORA', department: 11 },
  { _id: 215, description: 'NARANJAL', department: 11 },
  { _id: 216, description: 'SANTA ROSA DEL MONDAY', department: 11 },
  { _id: 217, description: 'IRUÑA', department: 11 },
  { _id: 219, description: 'MBARACAYU', department: 11 },
  { _id: 239, description: 'SANTA FE DEL PARANA', department: 11 },
  { _id: 240, description: 'NUEVA ESPERANZA', department: 11 },
  { _id: 269, description: 'TAVAPY', department: 11 },
  { _id: 273, description: 'DR. RAUL PEÑA', department: 11 },
  { _id: 152, description: 'AREGUA', department: 12 },
  { _id: 153, description: 'CAPIATA', department: 12 },
  { _id: 154, description: 'FERNANDO DE LA MORA', department: 12 },
  { _id: 155, description: 'GUARAMBARE', department: 12 },
  { _id: 156, description: 'ITA', department: 12 },
  { _id: 157, description: 'ITAUGUA', department: 12 },
  { _id: 158, description: 'LIMPIO', department: 12 },
  { _id: 159, description: 'LUQUE', department: 12 },
  { _id: 160, description: 'MARIANO ROQUE ALONSO', department: 12 },
  { _id: 161, description: 'ÑEMBY', department: 12 },
  { _id: 162, description: 'NUEVA ITALIA', department: 12 },
  { _id: 163, description: 'SAN ANTONIO', department: 12 },
  { _id: 164, description: 'SAN LORENZO', department: 12 },
  { _id: 165, description: 'VILLA ELISA', department: 12 },
  { _id: 166, description: 'VILLETA', department: 12 },
  { _id: 167, description: 'YPACARAI', department: 12 },
  { _id: 168, description: 'YPANE', department: 12 },
  { _id: 169, description: 'LAMBARE', department: 12 },
  { _id: 170, description: 'J.AUGUSTO SALDIVAR', department: 12 },
  { _id: 277, description: 'LOMA PYTA', department: 12 },
  { _id: 171, description: 'PILAR', department: 13 },
  { _id: 172, description: 'ALBERDI', department: 13 },
  { _id: 173, description: 'CERRITO', department: 13 },
  { _id: 174, description: 'DESMOCHADOS', department: 13 },
  { _id: 175, description: 'GUAZU CUA', department: 13 },
  { _id: 176, description: 'HUMAITA', department: 13 },
  { _id: 177, description: 'ISLA UMBU', department: 13 },
  { _id: 178, description: 'LAURELES', department: 13 },
  { _id: 179, description: 'PASO DE PATRIA', department: 13 },
  { _id: 180, description: 'MAYOR J.D.MARTINEZ', department: 13 },
  { _id: 181, description: 'SAN JUAN DE ÑEEMBUCU', department: 13 },
  { _id: 182, description: 'TACUARAS', department: 13 },
  { _id: 183, description: 'VILLA OLIVA', department: 13 },
  { _id: 184, description: 'VILLALBIN', department: 13 },
  { _id: 203, description: 'GRAL.JOSE EDUVIGIS DIAZ', department: 13 },
  { _id: 205, description: 'VILLA FRANCA', department: 13 },
  { _id: 230, description: 'VILLA FRANCA', department: 13 },
  { _id: 231, description: 'VILLALBIN', department: 13 },
  { _id: 185, description: 'PEDRO JUAN CABALLERO', department: 14 },
  { _id: 186, description: 'BELLA VISTA', department: 14 },
  { _id: 187, description: 'CAPITAN BADO', department: 14 },
  { _id: 278, description: 'KARAPAI', department: 14 },
  { _id: 279, description: 'ZANJA PYTA', department: 14 },
  { _id: 188, description: 'VILLA HAYES', department: 15 },
  { _id: 189, description: 'BENJAMIN ACEVAL(MONTE SOCIEDAD', department: 15 },
  { _id: 190, description: 'PTO.PINAZCO', department: 15 },
  { _id: 191, description: 'NANAWA', department: 15 },
  { _id: 206, description: 'POZO COLORADO', department: 15 },
  { _id: 242, description: 'JOSE FALCON', department: 15 },
  { _id: 261, description: 'TTE. 1RO. IRALA FERNANDEZ', department: 15 },
  { _id: 264, description: 'TENIENTE ESTEBAN MARTINEZ', department: 15 },
  { _id: 192, description: 'MCAL.ESTIGARRIBIA', department: 16 },
  { _id: 193, description: 'BOQUERON', department: 16 },
  { _id: 194, description: 'PEDRO P.PEÑA', department: 16 },
  { _id: 234, description: 'GRAL. EUGENIO A. GARAY', department: 16 },
  { _id: 259, description: 'FILADELFIA', department: 16 },
  { _id: 260, description: 'LOMA PLATA', department: 16 },
  { _id: 195, description: 'FUERTE OLIMPO', department: 17 },
  { _id: 196, description: 'BAHIA NEGRA', department: 17 },
  { _id: 218, description: 'PUERTO CASADO', department: 17 },
  { _id: 223, description: 'PUERTO GUARANI', department: 17 },
  { _id: 233, description: 'MAYOR PABLO LAGERENZA', department: 17 },
  { _id: 266, description: 'CARMELO PERALTA', department: 17 },
  { _id: 197, description: 'SAN ISIDRO DEL CURUGUATY', department: 18 },
  { _id: 198, description: 'VILLA YGATIMI', department: 18 },
  { _id: 199, description: 'YPEJHU', department: 18 },
  { _id: 200, description: 'CORPUS CHRISTI', department: 18 },
  { _id: 201, description: 'ITANARA', department: 18 },
  { _id: 202, description: 'FRANCISCO CABALLERO ALVAREZ', department: 18 },
  { _id: 207, description: 'SALTO DEL GUAIRA', department: 18 },
  { _id: 235, description: 'LA PALOMA', department: 18 },
  { _id: 236, description: 'KATUETE', department: 18 },
  { _id: 238, description: 'NUEVA ESPERANZA', department: 18 },
  { _id: 241, description: 'YASY KAÑY', department: 18 },
  { _id: 271, description: 'YBYRAROBANA', department: 18 },
  { _id: 274, description: 'YBY PYTA', department: 18 },
  { _id: 283, description: 'MARACANA', department: 18 },
  { _id: 284, description: 'PUERTO ADELA', department: 18 },
]