import { BasicData } from '../services/constants.service';

export enum MeasurementUnit {
  UNIDAD = 77,
  KILOGRAMOS_S__METRO_CUADRADO = 79,
  KILOGRAMOS = 83,
  GRAMOS = 86,
  METROS = 87,
  MILILITROS = 88,
  LITROS = 89,
  MILIGRAMOS = 90,
  CENTIMETROS = 91,
  CENTIMETROS_CUADRADOS = 92,
  CENTIMETROS_CUBICOS = 93,
  PULGADAS = 94,
  MILIMETROS = 95,
  MILIMETROS_CUADRADOS = 96,
  ANO = 97,
  MES = 98,
  TONELADA = 99,
  HORA = 100,
  MINUTO = 101,
  DIA = 102,
  YARDAS = 103,
  DETERMINACION = 104,
  METROS_representation_MT = 108,
  METROS_CUADRADOS = 109,
  METROS_CUBICOS = 110,

  // VER: https://www.dnit.gov.py/documents/20123/420595/NT_E_KUATIA_023_MT_V150.pdf/9580922b-5dd5-60f9-4857-ae66a757898f?t=1724956850006
  BOVINAS = 111,
  CURIE = 112,
  DOCENA = 113,
  GALONES_US = 114,
  GRUESAS = 115,
  KILOGRAMO_BRUTO = 116,
  KITS = 117,
  MICROCURIE = 118,
  MILLICURIE = 119,
  MILLIAR = 120,
  PAR = 121,
  PIES = 122,
  PIES_CUADRADOS = 123,
  PIEZAS = 124,
  QUILATE = 125,
  RESMAS = 126,
  ROLLOS = 127,
  KILOWATT_HORA = 128,
  MAZOS = 129,
  TAMBORES = 130,
  CAJA = 131,
  JUEGO = 132,
  PAQUETE = 133,
  BOLSA = 134,
  DOCENA_PAR = 135,
  POTE = 136,
  FARDOS = 137,
  BULTO = 138,
  CESTA = 139,
  PESO_BASE = 140,

  RACION = 569,
  KILOMETROS = 625,
  METRO_LINEAL = 660,
  SEGUNDO = 666,
  UNIDAD_MEDIDA_GLOBAL = 885,
  HECTAREAS = 869,
  POR_MILAJE = 891,
  COSTO_POR_MIL = 2366,
  UNIDAD_INTERNACIONAL = 2329,
}

type Data = BasicData<MeasurementUnit> & { representation: string };

// TODO: TRIM PARA TODO ESO
export const measurementUnits: Data[] = [
  {
    _id: MeasurementUnit.UNIDAD,
    description: 'Unidad                      ',
    representation: 'UNI   ',
  },
  {
    _id: MeasurementUnit.KILOGRAMOS_S__METRO_CUADRADO,
    description: 'Kilogramos s/ metro cuadrado',
    representation: 'kg/m2 ',
  },
  {
    _id: MeasurementUnit.KILOGRAMOS,
    description: 'Kilogramos                  ',
    representation: 'kg    ',
  },
  {
    _id: MeasurementUnit.GRAMOS,
    description: 'Gramos                      ',
    representation: 'g     ',
  },
  {
    _id: MeasurementUnit.METROS,
    description: 'Metros                      ',
    representation: 'm     ',
  },
  {
    _id: MeasurementUnit.MILILITROS,
    description: 'Mililitros                  ',
    representation: 'ML    ',
  },
  {
    _id: MeasurementUnit.LITROS,
    description: 'Litros                      ',
    representation: 'LT    ',
  },
  {
    _id: MeasurementUnit.MILIGRAMOS,
    description: 'Miligramos                  ',
    representation: 'MG    ',
  },
  {
    _id: MeasurementUnit.CENTIMETROS,
    description: 'Centimetros                 ',
    representation: 'CM    ',
  },
  {
    _id: MeasurementUnit.CENTIMETROS_CUADRADOS,
    description: 'Centimetros cuadrados       ',
    representation: 'CM2   ',
  },
  {
    _id: MeasurementUnit.CENTIMETROS_CUBICOS,
    description: 'Centimetros cubicos         ',
    representation: 'CM3   ',
  },
  {
    _id: MeasurementUnit.PULGADAS,
    description: 'Pulgadas                    ',
    representation: 'PUL   ',
  },
  {
    _id: MeasurementUnit.MILIMETROS,
    description: 'Milímetros                  ',
    representation: 'MM    ',
  },
  {
    _id: MeasurementUnit.MILIMETROS_CUADRADOS,
    description: 'Milímetros cuadrados        ',
    representation: 'MM2   ',
  },
  {
    _id: MeasurementUnit.ANO,
    description: 'Año                         ',
    representation: 'AA    ',
  },
  {
    _id: MeasurementUnit.MES,
    description: 'Mes                         ',
    representation: 'ME    ',
  },
  {
    _id: MeasurementUnit.TONELADA,
    description: 'Tonelada                    ',
    representation: 'TN    ',
  },
  {
    _id: MeasurementUnit.HORA,
    description: 'Hora                        ',
    representation: 'Hs    ',
  },
  {
    _id: MeasurementUnit.MINUTO,
    description: 'Minuto                      ',
    representation: 'Mi    ',
  },
  {
    _id: MeasurementUnit.DIA,
    description: 'Día                         ',
    representation: 'Di    ',
  },
  {
    _id: MeasurementUnit.YARDAS,
    description: 'Yardas                      ',
    representation: 'Ya    ',
  },
  {
    _id: MeasurementUnit.DETERMINACION,
    description: 'Determinación               ',
    representation: 'DET   ',
  },
  {
    _id: MeasurementUnit.METROS_representation_MT,
    description: 'Metros                      ',
    representation: 'MT    ',
  },
  {
    _id: MeasurementUnit.METROS_CUADRADOS,
    description: 'Metros cuadrados            ',
    representation: 'M2    ',
  },
  {
    _id: MeasurementUnit.METROS_CUBICOS,
    description: 'Metros cúbicos              ',
    representation: 'M3    ',
  },
  { _id: 111, representation: '4A ', description: 'Bovinas' },
  { _id: 112, representation: 'Ci ', description: 'Curie' },
  { _id: 113, representation: 'DOC', description: 'Docena' },
  { _id: 114, representation: 'GLL', description: 'Galones (US) (3,7843 LT)' },
  { _id: 115, representation: 'GRO', description: 'Gruesas' },
  { _id: 116, representation: 'E4 ', description: 'Kilogramo Bruto' },
  { _id: 117, representation: 'KT ', description: 'Kits' },
  { _id: 118, representation: 'M5 ', description: 'Microcurie' },
  { _id: 119, representation: 'MCU', description: 'Milicurie' },
  { _id: 120, representation: 'MIL', description: 'Millar' },
  { _id: 121, representation: 'PAR', description: 'Par' },
  { _id: 122, representation: 'FOT', description: 'Pies' },
  { _id: 123, representation: 'FTK', description: 'Pies Cuadradas' },
  { _id: 124, representation: 'PCE', description: 'Piezas' },
  { _id: 125, representation: 'KLT', description: 'Quilate' },
  { _id: 126, representation: 'RM ', description: 'Resmas' },
  { _id: 127, representation: 'RO ', description: 'Rollos' },
  { _id: 128, representation: 'kWh', description: '1000 Kilowatt Hora' },
  { _id: 129, representation: 'U(JGO)', description: ' Mazos' },
  { _id: 130, representation: 'DR ', description: 'Tambores' },
  { _id: 131, representation: 'BX ', description: 'Caja' },
  { _id: 132, representation: 'SET', description: 'Juego' },
  { _id: 133, representation: 'PK ', description: 'Paquete' },
  { _id: 134, representation: 'BG ', description: 'Bolsa' },
  { _id: 135, representation: 'DPC', description: 'Docena Par' },
  { _id: 136, representation: 'JR ', description: 'Pote' },
  { _id: 137, representation: 'BL ', description: 'Fardos' },
  { _id: 138, representation: 'AB ', description: 'Bulto' },
  { _id: 139, representation: 'BK ', description: 'Cesta' },
  { _id: 140, representation: 'BW ', description: 'Peso Base' },
  {
    _id: MeasurementUnit.RACION,
    description: 'Ración                      ',
    representation: 'ración',
  },
  {
    _id: MeasurementUnit.KILOMETROS,
    description: 'Kilómetros                  ',
    representation: 'Km    ',
  },
  {
    _id: MeasurementUnit.METRO_LINEAL,
    description: 'Metro lineal                ',
    representation: 'ml    ',
  },
  {
    _id: MeasurementUnit.SEGUNDO,
    description: 'Segundo                     ',
    representation: 'Se    ',
  },
  {
    _id: MeasurementUnit.UNIDAD_MEDIDA_GLOBAL,
    description: 'Unidad Medida Global        ',
    representation: 'GL    ',
  },
  {
    _id: MeasurementUnit.HECTAREAS,
    description: 'Hectáreas                   ',
    representation: 'ha    ',
  },
  {
    _id: MeasurementUnit.POR_MILAJE,
    description: 'Por Milaje                  ',
    representation: 'pm    ',
  },
  {
    _id: MeasurementUnit.COSTO_POR_MIL,
    description: 'Costo por Mil               ',
    representation: 'CPM   ',
  },
  {
    _id: MeasurementUnit.UNIDAD_INTERNACIONAL,
    description: 'Unidad Internacional        ',
    representation: 'UI    ',
  },
];
