import { BasicData } from '../services/constants.service';

export enum Obligation {
  IMPUESTO_A_LA_RENTA_IRACIS___REGIMENES_ESPECIALES = 113,
  TRIBUTO_UNICO_MAQUILA = 143,
  IMPUESTO_AL_VALOR_AGREGADO___GRAVADAS_Y_EXONERADAS___EXPORTADORES = 211,
  IMPUESTO_SELECTIVO_AL_CONSUMO___GENERAL = 311,
  IMPUESTO_SELECTIVO_AL_CONSUMO_COMBUSTIBLES = 321,
  IMPUESTO_A_LA_RENTA_EMPRESARIAL___REGIMEN_GENERAL = 700,
  IMPUESTO_A_LA_RENTA_EMPRESARIAL___SIMPLE = 701,
  IMPUESTO_DE_ZONA_FRANCA = 703,
  IMPUESTO_A_LA_RENTA_EMPRESARIAL___RESIMPLE = 702,
  IMPUESTO_A_LA_RENTA_PERSONAL___SERVICIOS_PERSONALES = 715,
  IMPUESTO_A_LA_RENTA_PERSONAL___RENTAS_Y_GANANCIAS_DE_CAPITAL = 716,
}

export const obligations: BasicData<Obligation>[] = [
  {
    code: Obligation.IMPUESTO_A_LA_RENTA_IRACIS___REGIMENES_ESPECIALES,
    description: 'IMPUESTO A LA RENTA IRACIS - REGÍMENES ESPECIALES',
  },
  {
    code: Obligation.TRIBUTO_UNICO_MAQUILA,
    description: 'TRIBUTO UNICO MAQUILA',
  },
  {
    code: Obligation.IMPUESTO_AL_VALOR_AGREGADO___GRAVADAS_Y_EXONERADAS___EXPORTADORES,
    description: 'IMPUESTO AL VALOR AGREGADO - GRAVADAS Y EXONERADAS - EXPORTADORES',
  },
  {
    code: Obligation.IMPUESTO_SELECTIVO_AL_CONSUMO___GENERAL,
    description: 'IMPUESTO SELECTIVO AL CONSUMO - GENERAL',
  },
  {
    code: Obligation.IMPUESTO_SELECTIVO_AL_CONSUMO_COMBUSTIBLES,
    description: 'IMPUESTO SELECTIVO AL CONSUMO COMBUSTIBLES',
  },
  {
    code: Obligation.IMPUESTO_A_LA_RENTA_EMPRESARIAL___REGIMEN_GENERAL,
    description: 'IMPUESTO A LA RENTA EMPRESARIAL - RÉGIMEN GENERAL',
  },
  {
    code: Obligation.IMPUESTO_A_LA_RENTA_EMPRESARIAL___SIMPLE,
    description: 'IMPUESTO A LA RENTA EMPRESARIAL - SIMPLE',
  },
  {
    code: Obligation.IMPUESTO_DE_ZONA_FRANCA,
    description: 'IMPUESTO DE ZONA FRANCA',
  },
  {
    code: Obligation.IMPUESTO_A_LA_RENTA_EMPRESARIAL___RESIMPLE,
    description: 'IMPUESTO A LA RENTA EMPRESARIAL - RESIMPLE',
  },
  {
    code: Obligation.IMPUESTO_A_LA_RENTA_PERSONAL___SERVICIOS_PERSONALES,
    description: 'IMPUESTO A LA RENTA PERSONAL - SERVICIOS PERSONALES',
  },
  {
    code: Obligation.IMPUESTO_A_LA_RENTA_PERSONAL___RENTAS_Y_GANANCIAS_DE_CAPITAL,
    description: 'IMPUESTO A LA RENTA PERSONAL - RENTAS Y GANANCIAS DE CAPITAL',
  },
];
