export enum SIFENEvent {
  CANCELACION = 1,

  //A futuro?
  INUTILIZACION = 2,

  //A futuro
  // ENDOSO = 3,
  
  CONFORMIDAD = 11,
  DISCONFORMIDAD = 12,
  DESCONOCIMIENTO = 13,
  NOTIFICACION = 14,
  NOMINACION = 15,
  ACTUALIZACION_DATOS_TRANSPORTE = 16,
}